# -*- coding: utf-8 -*-
"""Introduction to Data Analysis - Working with Real Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fj5t1PcKOFgjEi557Vl6H_pygutxV5wv
"""

# Import pandas library
# Pandas is used for data analysis and working with datasets
import pandas as pd

# Step 1: Load the dataset
# Read the CSV file using pandas
df = pd.read_csv("sales_data.csv")

# Step 2: Explore the dataset
# Display first 5 rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# Show dataset shape (rows, columns)
print("\nDataset Shape:")
print(df.shape)

# Show column names and data types
print("\nDataset Information:")
print(df.info())

# Step 3: Data Cleaning

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicate rows if any
df = df.drop_duplicates()

# Step 4: Sales Analysis

# Metric 1: Total Revenue
total_revenue = df["Total_Sales"].sum()

# Metric 2: Average Sales
average_sales = df["Total_Sales"].mean()

# Metric 3: Best Selling Product (based on quantity sold)
best_product = df.groupby("Product")["Quantity"].sum().idxmax()

# Metric 4: Maximum single order sale
max_sale = df["Total_Sales"].max()

# Step 5: Display formatted report
print("\n------ SALES ANALYSIS REPORT ------")

print(f"Total Revenue: ₹{total_revenue:,.2f}")
print(f"Average Order Value: ₹{average_sales:,.2f}")
print(f"Best Selling Product: {best_product}")
print(f"Highest Single Order Sale: ₹{max_sale:,.2f}")

print("\nReport generated successfully!")

